In [4]:
import pandas as pd
import re
df =  pd.read_csv("results.csv") #games between national teams
df["date"] = pd.to_datetime(df["date"])
df = df[(df["date"] >= "2018-8-1")].reset_index(drop=True) #games at the 2022 wc cycle
df_wc = df #pre-wc outcomes

rank = pd.read_csv("fifa_ranking-2023-07-20.csv") #rankings
rank["rank_date"] = pd.to_datetime(rank["rank_date"]) 
rank = rank[(rank["rank_date"] >= "2018-8-1")].reset_index(drop=True) #selecting games from the 2022 wc cycle
rank["country_full"] = rank["country_full"].str.replace("IR Iran", "Iran").str.replace("Korea Republic", "South Korea").str.replace("USA", "United States") #ajustando nomes de algumas seleções
rank = rank.set_index(['rank_date']).groupby(['country_full'], group_keys=False).resample('D').first().fillna(method='ffill').reset_index()
rank_wc = rank #dataframe with rankings

#Making the merge
df_wc_ranked = df_wc.merge(rank[["country_full", "total_points", "previous_points", "rank", "rank_change", "rank_date"]], left_on=["date", "home_team"], right_on=["rank_date", "country_full"]).drop(["rank_date", "country_full"], axis=1)
df_wc_ranked = df_wc_ranked.merge(rank[["country_full", "total_points", "previous_points", "rank", "rank_change", "rank_date"]], left_on=["date", "away_team"], right_on=["rank_date", "country_full"], suffixes=("_home", "_away")).drop(["rank_date", "country_full"], axis=1)

/tmp/ipykernel_2496/2233862965.py:12: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  rank = rank.set_index(['rank_date']).groupby(['country_full'], group_keys=False).resample('D').first().fillna(method='ffill').reset_index()

In [19]:
df =  pd.read_csv("results.csv") #games between national teams
df["date"] = pd.to_datetime(df["date"])
df = df[(df["date"] >= "2018-8-1")].reset_index(drop=True) #games at the 2022 wc cycle
df_wc = df

rank = pd.read_csv("fifa_ranking-2023-07-20.csv") #rankings
rank["rank_date"] = pd.to_datetime(rank["rank_date"]) 
rank = rank[(rank["rank_date"] >= "2018-8-1")].reset_index(drop=True) #selecting games from the 2022 wc cycle
rank["country_full"] = rank["country_full"].str.replace("IR Iran", "Iran").str.replace("Korea Republic", "South Korea").str.replace("USA", "United States") #ajustando nomes de algumas seleções

In [35]:
a=rank.set_index(['rank_date']).groupby(['country_full'], group_keys=False).resample('D').first().fillna(method='ffill')

/tmp/ipykernel_2496/3097257085.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  a=rank.set_index(['rank_date']).groupby(['country_full'], group_keys=False).resample('D').first().fillna(method='ffill')

In [36]:
a

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation
rank_date,,,,,,,
2018-08-16,145.0,Afghanistan,AFG,1068.00,1068.00,0.0,AFC
2018-08-17,145.0,Afghanistan,AFG,1068.00,1068.00,0.0,AFC
2018-08-18,145.0,Afghanistan,AFG,1068.00,1068.00,0.0,AFC
2018-08-19,145.0,Afghanistan,AFG,1068.00,1068.00,0.0,AFC
2018-08-20,145.0,Afghanistan,AFG,1068.00,1068.00,0.0,AFC
...,...,...,...,...,...,...,...
2023-07-16,124.0,Zimbabwe,ZIM,1138.56,1138.56,-2.0,CAF
2023-07-17,124.0,Zimbabwe,ZIM,1138.56,1138.56,-2.0,CAF
2023-07-18,124.0,Zimbabwe,ZIM,1138.56,1138.56,-2.0,CAF
2023-07-19,124.0,Zimbabwe,ZIM,1138.56,1138.56,-2.0,CAF
2023-07-20,125.0,Zimbabwe,ZIM,1138.56,1138.56,1.0,CAF

In [14]:
rank = rank.set_index(['rank_date']).groupby(['country_full'], group_keys=False).resample('D').first().fillna(method='ffill').reset_index()

,index,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,0,2018-08-04,Belize,Barbados,1,0,Friendly,San Pedro,Belize,False
1,1,2018-08-04,Palestine,Iraq,0,3,Friendly,Al-Ram,Palestine,False
2,2,2018-08-15,Guatemala,Cuba,3,0,Friendly,Guatemala City,Guatemala,False
3,3,2018-08-18,Andorra,United Arab Emirates,0,0,Friendly,Grödig,Austria,True
4,4,2018-08-18,Grenada,Jamaica,1,5,Friendly,St. George's,Grenada,False
...,...,...,...,...,...,...,...,...,...,...
5118,5118,2024-02-07,Ivory Coast,DR Congo,1,0,African Cup of Nations,Ebimpé,Ivory Coast,False
5119,5119,2024-02-07,Nigeria,South Africa,1,1,African Cup of Nations,Bouaké,Ivory Coast,True
5120,5120,2024-02-10,Qatar,Jordan,3,1,AFC Asian Cup,Lusail,Qatar,False
5121,5121,2024-02-10,South Africa,DR Congo,0,0,African Cup of Nations,Abidjan,Ivory Coast,True
5122,5122,2024-02-11,Ivory Coast,Nigeria,2,1,African Cup of Nations,Ebimpé,Ivory Coast,False